# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 10:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20161121_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 21, 10, 30, 47, 203933, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
